### PR TITLE
smfc: fix redefinition of 'operator<<'

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

CPP generator will generate mulitple definitions of 'operator<<' for one service if the `fbs` contains more than one service.

### CODE REVIEW

**Review by senior7515 — APPROVED** [review]
LGTM. So is the gist, thata the `services` was listed 2x? must have been a merge skew.

**Comment by senior7515** [comment]
@youjiali1995 thanks for the patch. can you ammend the commit to explain the change (redefinition of services)

**Comment by youjiali1995** [comment]
@senior7515 PTAL, thanks!
